### ISSUE TITLE
pip install does not work

### ISSUE THREAD

**Issue by sebastianJaeger** [ComPWA/pycompwa#51]
```
pip install pycompwa
Collecting pycompwa
  Using cached https://files.pythonhosted.org/packages/3b/92/a62d2192624f31493530a94e38dfe033b77b0a24f3a139c2c8a99640d6c2/pycompwa-0.1.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Searching for cmake
    Reading https://pypi.org/simple/cmake/
    Downloading https://files.pythonhosted.org/packages/a5/7c/6525cadf99abbabbcb29676f53de0441e8d2f8d0114ab52aae2b31223a3b/cmake-3.16.3.tar.gz#sha256=6fadcaef9b52be35c26d52d9701dd031e96db06231964a5dc29f5d2155285da8
    Best match: cmake 3.16.3
    Processing cmake-3.16.3.tar.gz
    Writing /tmp/easy_install-ltdnbqii/cmake-3.16.3/setup.cfg
    Running cmake-3.16.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ltdnbqii/cmake-3.16.3/egg-dist-tmp-f7nku42m
    /home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/dist.py:470: UserWarning: Normalizing '0.1.00' to '0.1.0'
      normalized_version,
    Traceback (most recent call last):
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-ltdnbqii/cmake-3.16.3/setup.py", line 78, in <module>
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/skbuild/setuptools_wrap.py", line 425, in setup
        _parse_setuptools_arguments(kw)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/skbuild/setuptools_wrap.py", line 212, in _parse_setuptools_arguments
        for cmd in [dist.get_command_obj(command) for command in dist.commands]:
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/skbuild/setuptools_wrap.py", line 212, in <listcomp>
        for cmd in [dist.get_command_obj(command) for command in dist.commands]:
      File "/usr/lib64/python3.6/distutils/dist.py", line 847, in get_command_obj
        cmd_obj = self.command_obj[command] = klass(self)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/__init__.py", line 161, in __init__
        _Command.__init__(self, dist)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 57, in __init__
        raise TypeError("dist must be a Distribution instance")
    TypeError: dist must be a Distribution instance
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xt_l36ze/pycompwa/setup.py", line 42, in <module>
        'uproot'],
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/skbuild/setuptools_wrap.py", line 456, in setup
        return upstream_setup(*args, **kw)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/__init__.py", line 142, in setup
        _install_setup_requires(attrs)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/__init__.py", line 137, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/dist.py", line 586, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 780, in resolve
        replace_conflicting=replace_conflicting
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1063, in best_match
        return self.obtain(req, installer)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1075, in obtain
        return installer(requirement)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/dist.py", line 653, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-ltdnbqii/cmake-3.16.3/setup.py", line 78, in <module>
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/skbuild/setuptools_wrap.py", line 425, in setup
        _parse_setuptools_arguments(kw)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/skbuild/setuptools_wrap.py", line 212, in _parse_setuptools_arguments
        for cmd in [dist.get_command_obj(command) for command in dist.commands]:
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/skbuild/setuptools_wrap.py", line 212, in <listcomp>
        for cmd in [dist.get_command_obj(command) for command in dist.commands]:
      File "/usr/lib64/python3.6/distutils/dist.py", line 847, in get_command_obj
        cmd_obj = self.command_obj[command] = klass(self)
      File "/home/tau/sjaeger/compwa/lib64/python3.6/site-packages/setuptools/__init__.py", line 161, in __init__
        _Command.__init__(self, dist)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 57, in __init__
        raise TypeError("dist must be a Distribution instance")
    TypeError: dist must be a Distribution instance
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-xt_l36ze/pycompwa/

```

**Comment by spflueger** [comment]
Ok, thanks for pointing it out. There were some "releases" made before, but they are not release-worthy in my opinion. So I will delete those releases again... For now you should work only with `git clone` and `git pull/fetch` etc

**Comment by redeboer** [comment]
https://travis-ci.com/github/ComPWA/pycompwa/jobs/321210933
